Repository WildCodeSchool/2023-02-js-btz-spotcast, pull requests merged in 2023-04, with the labels that each got.

#4 Wind component with API connection finished
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/components/widgets/cards.css
  src/components/widgets/wind/Wind.css
  src/components/widgets/wind/Wind.jsx
  src/index.js
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
Labels: Changes done

#6 Architecture refactoring
  .gitignore
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/fonts/N27-Regular.otf
  src/components/forecast-cards/ForecastCardBackground.css
  src/components/forecast-cards/ForecastCardBackground.jsx
  src/components/forecast-cards/forecast-card-extended/ForecastCardExtended.css
  src/components/forecast-cards/forecast-card-extended/ForecastCardExtended.jsx
  src/components/forecast-cards/forecast-card-minified/ForecastCardMinified.css
  src/components/forecast-cards/forecast-card-minified/ForecastCardMinified.jsx
  src/components/utilities/ToggleButton.css
  src/components/utilities/ToggleButton.jsx
  src/components/widgets/cards.css
  src/components/widgets/wind/Wind.css
  src/components/widgets/wind/Wind.jsx
  src/index.js
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
Labels: Reviewed

#7 creation bckg card + generation APi pour data de la card + liaison avec spot récupérer dans searchbar
  src/assets/etoile-32px.png
  src/assets/marqueur-32px.png
  src/components/forecast-cards/ForecastCardBackground.css
  src/components/forecast-cards/ForecastCardBackground.jsx
  src/components/utilities/tide.json
  src/pages/Dashboard.jsx
Labels: Reviewed

#8 NavBar done and merged onto Dev latest
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/assets/logo-header.svg
  src/assets/logo.png
  src/assets/rodrigo.jpg
  src/components/utilities/RateButton.jsx
  src/components/utilities/SpotDataBase.jsx
  src/components/widgets/cards.css
  src/components/widgets/navbar/NavBar.css
  src/components/widgets/navbar/NavBar.jsx
  src/components/widgets/navbar/searchbar/SearchBar.jsx
  src/pages/Dashboard.jsx
Labels: Reviewed

#9 Sunset component done and stylized
  src/assets/images/aube.svg
  src/assets/images/crepuscule.svg
  src/assets/images/sunset-separator.svg
  src/components/utilities/ToggleButton.css
  src/components/widgets/sunset/Sunset.css
  src/components/widgets/sunset/Sunset.jsx
  src/components/widgets/wind/Wind.jsx
  src/pages/Dashboard.jsx
Labels: Reviewed

#10 Tide widget done and Stylized
  git-commande.txt
  src/App.js
  src/components/widgets/tide/Tide.css
  src/components/widgets/tide/Tide.jsx
  src/components/widgets/tide/TideDatas.jsx
  src/components/widgets/wind/Wind.jsx
  src/pages/Dashboard.jsx
  src/tide-shape.svg
Labels: Conflicts

#11 S01 nav bar
  src/assets/images/star-filled.svg
  src/assets/images/star-outline.svg
  src/components/utilities/RateButton.jsx
  src/components/widgets/navbar/NavBar.css
  src/components/widgets/navbar/searchbar/SearchBar.jsx
  src/pages/Dashboard.jsx
Labels: Reviewed

#13 Dashboard styling
  src/App.css
  src/assets/images/star-filled.svg
  src/assets/images/star-outline.svg
  src/components/widgets/navbar/NavBar.css
  src/components/widgets/tide/TideDatas.jsx
  src/components/widgets/wind/Wind.jsx
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
Labels: Reviewed

#15 Meteo component bis
  package-lock.json
  package.json
  src/App.css
  src/assets/images/neige.svg
  src/assets/images/nuages.svg
  src/assets/images/pluie.svg
  src/assets/images/soleil-nuages.svg
  src/assets/images/soleil.svg
  src/assets/images/vent.svg
  src/components/widgets/meteo-day/MeteoDay.css
  src/components/widgets/meteo-day/MeteoDay.jsx
  src/components/widgets/meteo-three-day/MeteoThreeDay.css
  src/components/widgets/meteo-three-day/MeteoThreeDay.jsx
  src/components/widgets/meteo-three-day/components/DateThreeDays.jsx
  src/components/widgets/meteo-three-day/components/IconMeteoThreeDays.jsx
  src/components/widgets/meteo-three-day/components/TempThreeDays.jsx
  src/pages/Dashboard.jsx
Labels: Reviewed

#22 Login feature done
  package-lock.json
  package.json
  src/components/utilities/SpotDataBase.jsx
  src/components/utilities/UsersDataBase.jsx
  src/components/widgets/login/Login.css
  src/components/widgets/login/Login.jsx
  src/components/widgets/login/Register.jsx
  src/components/widgets/navbar/NavBar.css
  src/components/widgets/navbar/NavBar.jsx
  src/pages/Dashboard.css
  src/pages/Dashboard.jsx
Labels: Reviewed
